# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/tpu_double/tpu_receive/tpu_receive.srcs/sources_1/ip/tpu_receive_clock/tpu_receive_clock.xci
# IP: The module: 'tpu_receive_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tpu_double/tpu_receive/tpu_receive.srcs/sources_1/ip/tpu_receive_clock/tpu_receive_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tpu_receive_clock'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/tpu_double/tpu_receive/tpu_receive.srcs/sources_1/ip/tpu_receive_clock/tpu_receive_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'tpu_receive_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/tpu_double/tpu_receive/tpu_receive.srcs/sources_1/ip/tpu_receive_clock/tpu_receive_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tpu_receive_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/tpu_double/tpu_receive/tpu_receive.srcs/sources_1/ip/tpu_receive_clock/tpu_receive_clock.xci
# IP: The module: 'tpu_receive_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tpu_double/tpu_receive/tpu_receive.srcs/sources_1/ip/tpu_receive_clock/tpu_receive_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tpu_receive_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/tpu_double/tpu_receive/tpu_receive.srcs/sources_1/ip/tpu_receive_clock/tpu_receive_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'tpu_receive_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/tpu_double/tpu_receive/tpu_receive.srcs/sources_1/ip/tpu_receive_clock/tpu_receive_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tpu_receive_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
