# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/dds_rq/dds_rq.xci
# IP: The module: 'dds_rq' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/dds_rq/dds_rq_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_rq'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/dds_rq/dds_rq.xci
# IP: The module: 'dds_rq' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/dds_rq/dds_rq_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_rq'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
