# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dell/Desktop/TPU_pr/tpu_fs/tpu.srcs/sources_1/ip/fir_compiler_t/fir_compiler_t.xci
# IP: The module: 'fir_compiler_t' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/TPU_pr/tpu_fs/tpu.srcs/sources_1/ip/fir_compiler_t/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_t'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dell/Desktop/TPU_pr/tpu_fs/tpu.srcs/sources_1/ip/fir_compiler_t/fir_compiler_t_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_t'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/dell/Desktop/TPU_pr/tpu_fs/tpu.srcs/sources_1/ip/fir_compiler_t/fir_compiler_t.xci
# IP: The module: 'fir_compiler_t' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/TPU_pr/tpu_fs/tpu.srcs/sources_1/ip/fir_compiler_t/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_t'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dell/Desktop/TPU_pr/tpu_fs/tpu.srcs/sources_1/ip/fir_compiler_t/fir_compiler_t_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_t'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
