#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun May 24 19:44:12 PDT 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tpu_th_behav -key {Behavioral:sim_1:Functional:tpu_th} -tclbatch tpu_th.tcl -view /home/caohy/work/tpu_kcu105/tpu_th_behav.wcfg -log simulate.log"
xsim tpu_th_behav -key {Behavioral:sim_1:Functional:tpu_th} -tclbatch tpu_th.tcl -view /home/caohy/work/tpu_kcu105/tpu_th_behav.wcfg -log simulate.log

