#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : mySystem.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Jan 08 15:59:15 +0800 2020
# SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: mySystem.sh [-help]
# usage: mySystem.sh [-lib_map_path]
# usage: mySystem.sh [-noclean_files]
# usage: mySystem.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'mySystem.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xpm gtwizard_ultrascale_v1_7_7 xil_defaultlib jesd204_v7_2_7 xlconstant_v1_1_6 util_vector_logic_v2_0_1 xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 dds_compiler_v6_0_19 xlconcat_v2_1_3)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "mySystem.sh - Script generated by export_simulation (Vivado v2019.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/4fba" \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work gtwizard_ultrascale_v1_7_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/4fba" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/4fba" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/sim/gtwizard_ultrascale_v1_7_gthe3_channel.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/sim/mySystem_jesd204_phy_0_gt_gthe3_channel_wrapper.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/sim/mySystem_jesd204_phy_0_gt_gtwizard_gthe3.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/sim/mySystem_jesd204_phy_0_gt_gtwizard_top.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/sim/mySystem_jesd204_phy_0_gt.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_block.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_sync_block.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_support.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_gt_common_wrapper.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/gtwizard_ultrascale_v1_7_gthe3_common.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_gt_common.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_reset_control.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work jesd204_v7_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/4fba" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/31f5/hdl/jesd204_v7_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/4fba" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0_block.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/axi_ipif/mySystem_jesd204_rx_0_address_decoder.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0_register_decode.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/axi_ipif/mySystem_jesd204_rx_0_axi_lite_ipif.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/axi_ipif/mySystem_jesd204_rx_0_counter_f.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/axi_ipif/mySystem_jesd204_rx_0_pselect_f.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/axi_ipif/mySystem_jesd204_rx_0_slave_attachment.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0_reset_block.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0.v" \
    "$ref_dir/../../../bd/mySystem/ipshared/58cb/sources_1/imports/leds/leds.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_leds_0_0/sim/mySystem_leds_0_0.v" \
    "$ref_dir/../../../bd/mySystem/ipshared/c646/sources_1/imports/iobufs_ti/iobufs_ti.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_iobufs_i_1/sim/mySystem_iobufs_i_1.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/4fba" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/34f7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/4fba" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlconstant_0_0/sim/mySystem_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlconstant_0_1/sim/mySystem_xlconstant_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/4fba" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/4fba" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_util_vector_logic_0_0/sim/mySystem_util_vector_logic_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b795/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/ce84/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work dds_compiler_v6_0_19 $vhdlan_opts \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/c3fd/hdl/dds_compiler_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_dds_compiler_0_0/sim/mySystem_dds_compiler_0_0.vhd" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_dds_compiler_0_1/sim/mySystem_dds_compiler_0_1.vhd" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_dds_compiler_0_2/sim/mySystem_dds_compiler_0_2.vhd" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_dds_compiler_0_3/sim/mySystem_dds_compiler_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/4fba" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ipshared/4fba" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlconcat_0_0/sim/mySystem_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_Transport_layer_DAC38Rf82_84111_0_1/sim/mySystem_Transport_layer_DAC38Rf82_84111_0_1.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_util_vector_logic_21_0/sim/mySystem_util_vector_logic_21_0.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_util_vector_logic_21_1/sim/mySystem_util_vector_logic_21_1.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_util_vector_logic_21_2/sim/mySystem_util_vector_logic_21_2.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_util_vector_logic_0_1/sim/mySystem_util_vector_logic_0_1.v" \
    "$ref_dir/../../../bd/mySystem/sim/mySystem.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.mySystem xil_defaultlib.glbl -o mySystem_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./mySystem_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./mySystem.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key mySystem_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc mySystem_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./mySystem.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: mySystem.sh [-help]\n\
Usage: mySystem.sh [-lib_map_path]\n\
Usage: mySystem.sh [-reset_run]\n\
Usage: mySystem.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
