# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/tpu_double/tpu_transmit/tpu_transmit.srcs/sources_1/new/axis_fifo_t/axis_fifo_t.xci
# IP: The module: 'axis_fifo_t' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tpu_double/tpu_transmit/tpu_transmit.srcs/sources_1/new/axis_fifo_t/axis_fifo_t_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_fifo_t'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/tpu_double/tpu_transmit/tpu_transmit.srcs/sources_1/new/axis_fifo_t/axis_fifo_t.xci
# IP: The module: 'axis_fifo_t' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tpu_double/tpu_transmit/tpu_transmit.srcs/sources_1/new/axis_fifo_t/axis_fifo_t_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_fifo_t'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
