# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/KCU105.xdc

# XDC: imports/constraints/KCU105_io_TI.xdc

# XDC: imports/constraints/KCU105_io.xdc

# Block Designs: bd/mySystem/mySystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem || ORIG_REF_NAME==mySystem}]

# IP: bd/mySystem/ip/mySystem_jesd204_phy_0/mySystem_jesd204_phy_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_jesd204_phy_0 || ORIG_REF_NAME==mySystem_jesd204_phy_0}]

# IP: bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/mySystem_jesd204_phy_0_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_jesd204_phy_0_gt || ORIG_REF_NAME==mySystem_jesd204_phy_0_gt}]

# IP: bd/mySystem/ip/mySystem_jesd204_rx_0/mySystem_jesd204_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_jesd204_rx_0 || ORIG_REF_NAME==mySystem_jesd204_rx_0}]

# IP: bd/mySystem/ip/mySystem_leds_0_0/mySystem_leds_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_leds_0_0 || ORIG_REF_NAME==mySystem_leds_0_0}]

# IP: bd/mySystem/ip/mySystem_iobufs_i_1/mySystem_iobufs_i_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_iobufs_i_1 || ORIG_REF_NAME==mySystem_iobufs_i_1}]

# IP: bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_clk_wiz_0_0 || ORIG_REF_NAME==mySystem_clk_wiz_0_0}]

# IP: bd/mySystem/ip/mySystem_xlconstant_0_0/mySystem_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlconstant_0_0 || ORIG_REF_NAME==mySystem_xlconstant_0_0}]

# IP: bd/mySystem/ip/mySystem_xlconstant_0_1/mySystem_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlconstant_0_1 || ORIG_REF_NAME==mySystem_xlconstant_0_1}]

# IP: bd/mySystem/ip/mySystem_util_vector_logic_0_0/mySystem_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_util_vector_logic_0_0 || ORIG_REF_NAME==mySystem_util_vector_logic_0_0}]

# IP: bd/mySystem/ip/mySystem_dds_compiler_0_0/mySystem_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_dds_compiler_0_0 || ORIG_REF_NAME==mySystem_dds_compiler_0_0}]

# IP: bd/mySystem/ip/mySystem_dds_compiler_0_1/mySystem_dds_compiler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_dds_compiler_0_1 || ORIG_REF_NAME==mySystem_dds_compiler_0_1}]

# IP: bd/mySystem/ip/mySystem_dds_compiler_0_2/mySystem_dds_compiler_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_dds_compiler_0_2 || ORIG_REF_NAME==mySystem_dds_compiler_0_2}]

# IP: bd/mySystem/ip/mySystem_dds_compiler_0_3/mySystem_dds_compiler_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_dds_compiler_0_3 || ORIG_REF_NAME==mySystem_dds_compiler_0_3}]

# IP: bd/mySystem/ip/mySystem_xlconcat_0_0/mySystem_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlconcat_0_0 || ORIG_REF_NAME==mySystem_xlconcat_0_0}]

# IP: bd/mySystem/ip/mySystem_Transport_layer_DAC38Rf82_84111_0_1/mySystem_Transport_layer_DAC38Rf82_84111_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_Transport_layer_DAC38Rf82_84111_0_1 || ORIG_REF_NAME==mySystem_Transport_layer_DAC38Rf82_84111_0_1}]

# IP: bd/mySystem/ip/mySystem_util_vector_logic_21_0/mySystem_util_vector_logic_21_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_util_vector_logic_21_0 || ORIG_REF_NAME==mySystem_util_vector_logic_21_0}]

# IP: bd/mySystem/ip/mySystem_util_vector_logic_21_1/mySystem_util_vector_logic_21_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_util_vector_logic_21_1 || ORIG_REF_NAME==mySystem_util_vector_logic_21_1}]

# IP: bd/mySystem/ip/mySystem_util_vector_logic_21_2/mySystem_util_vector_logic_21_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_util_vector_logic_21_2 || ORIG_REF_NAME==mySystem_util_vector_logic_21_2}]

# IP: bd/mySystem/ip/mySystem_util_vector_logic_0_1/mySystem_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_util_vector_logic_0_1 || ORIG_REF_NAME==mySystem_util_vector_logic_0_1}]

# XDC: bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/synth/mySystem_jesd204_phy_0_gt_ooc.xdc

# XDC: bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/synth/mySystem_jesd204_phy_0_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_jesd204_phy_0_gt || ORIG_REF_NAME==mySystem_jesd204_phy_0_gt}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_ooc.xdc

# XDC: bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_jesd204_phy_0 || ORIG_REF_NAME==mySystem_jesd204_phy_0}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_jesd204_phy_0 || ORIG_REF_NAME==mySystem_jesd204_phy_0}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_jesd204_rx_0 || ORIG_REF_NAME==mySystem_jesd204_rx_0}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0_ooc.xdc

# XDC: bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_clk_wiz_0_0 || ORIG_REF_NAME==mySystem_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_clk_wiz_0_0 || ORIG_REF_NAME==mySystem_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_clk_wiz_0_0 || ORIG_REF_NAME==mySystem_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0_ooc.xdc

# XDC: bd/mySystem/ip/mySystem_dds_compiler_0_0/mySystem_dds_compiler_0_0_ooc.xdc

# XDC: bd/mySystem/ip/mySystem_dds_compiler_0_1/mySystem_dds_compiler_0_1_ooc.xdc

# XDC: bd/mySystem/ip/mySystem_dds_compiler_0_2/mySystem_dds_compiler_0_2_ooc.xdc

# XDC: bd/mySystem/ip/mySystem_dds_compiler_0_3/mySystem_dds_compiler_0_3_ooc.xdc

# XDC: bd/mySystem/mySystem_ooc.xdc
