# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.cache/wt [current_project]
set_property parent.project_path D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kcu105:part0:1.1 [current_project]
set_property ip_repo_paths d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/local_IP_TI/repository [current_project]
add_files D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/sw_src/uhwd/Debug/uhwd_static.elf
set_property SCOPED_TO_REF core_name_ddr4_mem_intfc [get_files -all D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/sw_src/uhwd/Debug/uhwd_static.elf]
set_property SCOPED_TO_CELLS u_ddr_cal_riu/mcs0/microblaze_I [get_files -all D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/sw_src/uhwd/Debug/uhwd_static.elf]
add_files D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/sw_src/uhwd/Debug/uhwd_dhcp.elf
set_property SCOPED_TO_REF core_name_ddr4_mem_intfc [get_files -all D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/sw_src/uhwd/Debug/uhwd_dhcp.elf]
set_property SCOPED_TO_CELLS u_ddr_cal_riu/mcs0/microblaze_I [get_files -all D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/sw_src/uhwd/Debug/uhwd_dhcp.elf]
add_files D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/mySystem.bd
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/synth/mySystem_jesd204_phy_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/synth/mySystem_jesd204_phy_0_gt.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_dds_compiler_0_0/mySystem_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_dds_compiler_0_1/mySystem_dds_compiler_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_dds_compiler_0_2/mySystem_dds_compiler_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_dds_compiler_0_3/mySystem_dds_compiler_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/mySystem_ooc.xdc]
set_property is_locked true [get_files D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/mySystem.bd]

read_verilog -library xil_defaultlib {
  D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/new/Transport_layer_DAC38RF82_84111.v
  D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/hdl/mySystem_wrapper.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/constrs_1/imports/constraints/KCU105.xdc
set_property used_in_implementation false [get_files D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/constrs_1/imports/constraints/KCU105.xdc]

read_xdc D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/constrs_1/imports/constraints/KCU105_io_TI.xdc
set_property used_in_implementation false [get_files D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/constrs_1/imports/constraints/KCU105_io_TI.xdc]

read_xdc D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/constrs_1/imports/constraints/KCU105_io.xdc
set_property used_in_implementation false [get_files D:/Soliton_work/Xilinx/DAC38RF82/UltraScale_P7_T14/prj_MyKcu105_TI/prj_MyKcu105_TI.srcs/constrs_1/imports/constraints/KCU105_io.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top mySystem_wrapper -part xcku040-ffva1156-2-e


write_checkpoint -force -noxdef mySystem_wrapper.dcp

catch { report_utilization -file mySystem_wrapper_utilization_synth.rpt -pb mySystem_wrapper_utilization_synth.pb }
