set_property SRC_FILE_INFO {cfile:/home/caohy/work/kcu_10gbaser_tpu/10gbaser_trd.srcs/constrs_1/imports/constraints/kcu105_10gbaser.xdc rfile:../../../10gbaser_trd.srcs/constrs_1/imports/constraints/kcu105_10gbaser.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN8 [get_ports reset]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports refclk_n]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P6 [get_ports refclk_p]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F10 [get_ports CLK_125MHZ_N]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G10 [get_ports CLK_125MHZ_P]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
create_clock -name clk_250m -period 4 [get_nets tpu_clock_mm/clk_out1]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
create_clock -name clk_500m -period 2 [get_nets tpu_clock_mm/clk_out2]
