# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/tpu_double/tpu_receive/tpu_receive.srcs/sources_1/new/bb_interface_fifo/bb_interface_fifo.xci
# IP: The module: 'bb_interface_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tpu_double/tpu_receive/tpu_receive.srcs/sources_1/new/bb_interface_fifo/bb_interface_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bb_interface_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/tpu_double/tpu_receive/tpu_receive.srcs/sources_1/new/bb_interface_fifo/bb_interface_fifo.xci
# IP: The module: 'bb_interface_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tpu_double/tpu_receive/tpu_receive.srcs/sources_1/new/bb_interface_fifo/bb_interface_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bb_interface_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
