# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}


start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param chipscope.maxJobs 4
  create_project -in_memory -part xcvu9p-flga2104-2L-e
  set_property board_part xilinx.com:vcu118:part0:2.3 [current_project]
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir /home/caohy/tpu/tpu.cache/wt [current_project]
  set_property parent.project_path /home/caohy/tpu/tpu.xpr [current_project]
  set_property ip_output_repo /home/caohy/tpu/tpu.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO} [current_project]
  add_files -quiet /home/caohy/tpu/tpu.runs/synth_1/tpu.dcp
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/ddc_out_fifo/ddc_out_fifo.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/sub_ddc/sub_ddc.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/mult_ddc/mult_ddc.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/add_ddc/add_ddc.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/dds_rq/dds_rq.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/rs_decoder/rs_decoder.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/rs_encoder/rs_encoder.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/axis_fifo_t/axis_fifo_t.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/sub_duc/sub_duc.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/dds_125m_q/dds_125m_q.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/duc_out_fifo/duc_out_fifo.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/axis_fifo_t8/axis_fifo_t8.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/dds_125m_i/dds_125m_i.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/mult_duc/mult_duc.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/add_duc/add_duc.xci
  read_ip -quiet /home/caohy/tpu/tpu.srcs/sources_1/ip/dds_ri/dds_ri.xci
  link_design -top tpu -part xcvu9p-flga2104-2L-e
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force tpu_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file tpu_drc_opted.rpt -pb tpu_drc_opted.pb -rpx tpu_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force tpu_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file tpu_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file tpu_utilization_placed.rpt -pb tpu_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file tpu_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force tpu_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file tpu_drc_routed.rpt -pb tpu_drc_routed.pb -rpx tpu_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file tpu_methodology_drc_routed.rpt -pb tpu_methodology_drc_routed.pb -rpx tpu_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file tpu_power_routed.rpt -pb tpu_power_summary_routed.pb -rpx tpu_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file tpu_route_status.rpt -pb tpu_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file tpu_timing_summary_routed.rpt -pb tpu_timing_summary_routed.pb -rpx tpu_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file tpu_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file tpu_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file tpu_bus_skew_routed.rpt -pb tpu_bus_skew_routed.pb -rpx tpu_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force tpu_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

