# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 32
set_param chipscope.maxJobs 4
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/caohy/tpu_kcu105/tpu.cache/wt [current_project]
set_property parent.project_path /home/caohy/tpu_kcu105/tpu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kcu105:part0:1.6 [current_project]
set_property ip_output_repo /home/caohy/tpu_kcu105/tpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/caohy/tpu_kcu105/fir.coe
read_verilog -library xil_defaultlib -sv {
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/crc_detector.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/crc_generator.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/new/ddc.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/new/dec2.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/deintrlv.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/descrambler.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/new/duc.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/eqam.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/new/inter2.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/interleaver.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/layer1.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/layer1_receive.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/layer1_transmit.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/mac_block.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/mac_deblock.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/qam.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/radio.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/new/radio_receive.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/radio_transmit.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/scrambler.sv
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/tpu.sv
}
read_verilog -library xil_defaultlib {
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/crc24_calc_1bit.v
  /home/caohy/tpu_kcu105/tpu.srcs/sources_1/imports/tpu.srcs/crc24_insert_1bit.v
}
read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/add_ddc/add_ddc.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/add_ddc/add_ddc_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/add_duc/add_duc.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/add_duc/add_duc_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/axis_fifo_t/axis_fifo_t.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/axis_fifo_t/axis_fifo_t_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/axis_fifo_t8/axis_fifo_t8.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/axis_fifo_t8/axis_fifo_t8_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/ddc_out_fifo/ddc_out_fifo.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/ddc_out_fifo/ddc_out_fifo_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/dds_125m_i/dds_125m_i.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/dds_125m_i/dds_125m_i_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/dds_125m_q/dds_125m_q.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/dds_125m_q/dds_125m_q_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/dds_ri/dds_ri.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/dds_ri/dds_ri_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/dds_rq/dds_rq.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/dds_rq/dds_rq_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/duc_out_fifo/duc_out_fifo.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/duc_out_fifo/duc_out_fifo_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/mult_ddc/mult_ddc.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/mult_ddc/mult_ddc_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/mult_duc/mult_duc.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/mult_duc/mult_duc_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/rs_decoder/rs_decoder.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/rs_decoder/rs_decoder_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/rs_encoder/rs_encoder.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/rs_encoder/rs_encoder_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/sub_ddc/sub_ddc.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/sub_ddc/sub_ddc_ooc.xdc]

read_ip -quiet /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/sub_duc/sub_duc.xci
set_property used_in_implementation false [get_files -all /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/sub_duc/sub_duc_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top tpu -part xcku040-ffva1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef tpu.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file tpu_utilization_synth.rpt -pb tpu_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
