# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/mult_duc/mult_duc.xci
# IP: The module: 'mult_duc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/mult_duc/mult_duc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_duc'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/mult_duc/mult_duc.xci
# IP: The module: 'mult_duc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/mult_duc/mult_duc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_duc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
