# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/kcu105_10gbaser.xdc

# Block Designs: bd/mac_phy/mac_phy.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy || ORIG_REF_NAME==mac_phy} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_xlconstant_1b0_0/mac_phy_xlconstant_1b0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_1b0_0 || ORIG_REF_NAME==mac_phy_xlconstant_1b0_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_xlconstant_1b1_0/mac_phy_xlconstant_1b1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_1b1_0 || ORIG_REF_NAME==mac_phy_xlconstant_1b1_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_xlconstant_3b101_0/mac_phy_xlconstant_3b101_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_3b101_0 || ORIG_REF_NAME==mac_phy_xlconstant_3b101_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_xlconstant_8b0_0/mac_phy_xlconstant_8b0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_8b0_0 || ORIG_REF_NAME==mac_phy_xlconstant_8b0_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_ten_gig_eth_mac_ch1_0/mac_phy_ten_gig_eth_mac_ch1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_ten_gig_eth_mac_ch1_0 || ORIG_REF_NAME==mac_phy_ten_gig_eth_mac_ch1_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch1_0/mac_phy_ten_gig_eth_pcs_pma_ch1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_ten_gig_eth_pcs_pma_ch1_0 || ORIG_REF_NAME==mac_phy_ten_gig_eth_pcs_pma_ch1_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_ten_gig_eth_mac_ch0_0/mac_phy_ten_gig_eth_mac_ch0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_ten_gig_eth_mac_ch0_0 || ORIG_REF_NAME==mac_phy_ten_gig_eth_mac_ch0_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch0_0/mac_phy_ten_gig_eth_pcs_pma_ch0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_ten_gig_eth_pcs_pma_ch0_0 || ORIG_REF_NAME==mac_phy_ten_gig_eth_pcs_pma_ch0_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_system_ila_mac_phy1_0/mac_phy_system_ila_mac_phy1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_system_ila_mac_phy1_0 || ORIG_REF_NAME==mac_phy_system_ila_mac_phy1_0} -quiet] -quiet

# IP: C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/axis_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# XDC: bd/mac_phy/mac_phy_ooc.xdc
