# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/tpu_clock_mm/tpu_clock_mm.xci
# IP: The module: 'tpu_clock_mm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/tpu_clock_mm/tpu_clock_mm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tpu_clock_mm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/tpu_clock_mm/tpu_clock_mm.xdc
# XDC: The top module name and the constraint reference have the same name: 'tpu_clock_mm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/tpu_clock_mm/tpu_clock_mm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tpu_clock_mm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/tpu_clock_mm/tpu_clock_mm.xci
# IP: The module: 'tpu_clock_mm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/tpu_clock_mm/tpu_clock_mm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tpu_clock_mm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/tpu_clock_mm/tpu_clock_mm.xdc
# XDC: The top module name and the constraint reference have the same name: 'tpu_clock_mm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/tpu_clock_mm/tpu_clock_mm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tpu_clock_mm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
