# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ddc_out_fifo/ddc_out_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddc_out_fifo || ORIG_REF_NAME==ddc_out_fifo} -quiet] -quiet

# IP: ip/sub_ddc/sub_ddc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_ddc || ORIG_REF_NAME==sub_ddc} -quiet] -quiet

# IP: ip/mult_ddc/mult_ddc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_ddc || ORIG_REF_NAME==mult_ddc} -quiet] -quiet

# IP: ip/add_ddc/add_ddc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_ddc || ORIG_REF_NAME==add_ddc} -quiet] -quiet

# IP: ip/dds_rq/dds_rq.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_rq || ORIG_REF_NAME==dds_rq} -quiet] -quiet
