# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/KCU105.xdc

# XDC: imports/constraints/KCU105_io_TI.xdc

# XDC: imports/constraints/KCU105_io.xdc

# Block Designs: bd/mySystem/mySystem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem || ORIG_REF_NAME==mySystem}]

# IP: bd/mySystem/ip/mySystem_jesd204_phy_0/mySystem_jesd204_phy_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_jesd204_phy_0 || ORIG_REF_NAME==mySystem_jesd204_phy_0}]

# IP: bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/mySystem_jesd204_phy_0_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_jesd204_phy_0_gt || ORIG_REF_NAME==mySystem_jesd204_phy_0_gt}]

# IP: bd/mySystem/ip/mySystem_jesd204_rx_0/mySystem_jesd204_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_jesd204_rx_0 || ORIG_REF_NAME==mySystem_jesd204_rx_0}]

# IP: bd/mySystem/ip/mySystem_leds_0_0/mySystem_leds_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_leds_0_0 || ORIG_REF_NAME==mySystem_leds_0_0}]

# IP: bd/mySystem/ip/mySystem_iobufs_i_1/mySystem_iobufs_i_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_iobufs_i_1 || ORIG_REF_NAME==mySystem_iobufs_i_1}]

# IP: bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_clk_wiz_0_0 || ORIG_REF_NAME==mySystem_clk_wiz_0_0}]

# IP: bd/mySystem/ip/mySystem_xlconstant_0_0/mySystem_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlconstant_0_0 || ORIG_REF_NAME==mySystem_xlconstant_0_0}]

# IP: bd/mySystem/ip/mySystem_xlconstant_0_1/mySystem_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlconstant_0_1 || ORIG_REF_NAME==mySystem_xlconstant_0_1}]

# IP: bd/mySystem/ip/mySystem_util_vector_logic_0_0/mySystem_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_util_vector_logic_0_0 || ORIG_REF_NAME==mySystem_util_vector_logic_0_0}]

# IP: bd/mySystem/ip/mySystem_Transport_layer_12DJxx_0_0/mySystem_Transport_layer_12DJxx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_Transport_layer_12DJxx_0_0 || ORIG_REF_NAME==mySystem_Transport_layer_12DJxx_0_0}]

# IP: bd/mySystem/ip/mySystem_util_vector_logic_0_8/mySystem_util_vector_logic_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_util_vector_logic_0_8 || ORIG_REF_NAME==mySystem_util_vector_logic_0_8}]

# IP: bd/mySystem/ip/mySystem_xlslice_0_8/mySystem_xlslice_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_0_8 || ORIG_REF_NAME==mySystem_xlslice_0_8}]

# IP: bd/mySystem/ip/mySystem_xlslice_1_0/mySystem_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_1_0 || ORIG_REF_NAME==mySystem_xlslice_1_0}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_0/mySystem_xlslice_21_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_0 || ORIG_REF_NAME==mySystem_xlslice_21_0}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_1/mySystem_xlslice_21_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_1 || ORIG_REF_NAME==mySystem_xlslice_21_1}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_2/mySystem_xlslice_21_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_2 || ORIG_REF_NAME==mySystem_xlslice_21_2}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_3/mySystem_xlslice_21_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_3 || ORIG_REF_NAME==mySystem_xlslice_21_3}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_4/mySystem_xlslice_21_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_4 || ORIG_REF_NAME==mySystem_xlslice_21_4}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_5/mySystem_xlslice_21_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_5 || ORIG_REF_NAME==mySystem_xlslice_21_5}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_6/mySystem_xlslice_21_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_6 || ORIG_REF_NAME==mySystem_xlslice_21_6}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_7/mySystem_xlslice_21_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_7 || ORIG_REF_NAME==mySystem_xlslice_21_7}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_8/mySystem_xlslice_21_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_8 || ORIG_REF_NAME==mySystem_xlslice_21_8}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_9/mySystem_xlslice_21_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_9 || ORIG_REF_NAME==mySystem_xlslice_21_9}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_10/mySystem_xlslice_21_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_10 || ORIG_REF_NAME==mySystem_xlslice_21_10}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_11/mySystem_xlslice_21_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_11 || ORIG_REF_NAME==mySystem_xlslice_21_11}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_12/mySystem_xlslice_21_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_12 || ORIG_REF_NAME==mySystem_xlslice_21_12}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_13/mySystem_xlslice_21_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_13 || ORIG_REF_NAME==mySystem_xlslice_21_13}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_14/mySystem_xlslice_21_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_14 || ORIG_REF_NAME==mySystem_xlslice_21_14}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_15/mySystem_xlslice_21_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_15 || ORIG_REF_NAME==mySystem_xlslice_21_15}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_16/mySystem_xlslice_21_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_16 || ORIG_REF_NAME==mySystem_xlslice_21_16}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_17/mySystem_xlslice_21_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_17 || ORIG_REF_NAME==mySystem_xlslice_21_17}]

# IP: bd/mySystem/ip/mySystem_xlslice_21_18/mySystem_xlslice_21_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlslice_21_18 || ORIG_REF_NAME==mySystem_xlslice_21_18}]

# IP: bd/mySystem/ip/mySystem_xlconcat_0_2/mySystem_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlconcat_0_2 || ORIG_REF_NAME==mySystem_xlconcat_0_2}]

# IP: bd/mySystem/ip/mySystem_util_reduced_logic_1_3/mySystem_util_reduced_logic_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_util_reduced_logic_1_3 || ORIG_REF_NAME==mySystem_util_reduced_logic_1_3}]

# IP: bd/mySystem/ip/mySystem_xlconstant_0_2/mySystem_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mySystem_xlconstant_0_2 || ORIG_REF_NAME==mySystem_xlconstant_0_2}]

# XDC: bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/synth/mySystem_jesd204_phy_0_gt_ooc.xdc

# XDC: bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/synth/mySystem_jesd204_phy_0_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_jesd204_phy_0_gt || ORIG_REF_NAME==mySystem_jesd204_phy_0_gt}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_ooc.xdc

# XDC: bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_jesd204_phy_0 || ORIG_REF_NAME==mySystem_jesd204_phy_0}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_jesd204_phy_0 || ORIG_REF_NAME==mySystem_jesd204_phy_0}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_jesd204_rx_0 || ORIG_REF_NAME==mySystem_jesd204_rx_0}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0_ooc.xdc

# XDC: bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_clk_wiz_0_0 || ORIG_REF_NAME==mySystem_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_clk_wiz_0_0 || ORIG_REF_NAME==mySystem_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mySystem_clk_wiz_0_0 || ORIG_REF_NAME==mySystem_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0_ooc.xdc

# XDC: bd/mySystem/mySystem_ooc.xdc
