#!/bin/bash -f
# Vivado (TM) v2016.1 (64-bit)
#
# Filename    : mySystem.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Aug 18 06:21:37 -0500 2017
# IP Build 1537824 on Fri Apr  8 04:28:57 MDT 2016 
#
# usage: mySystem.sh [-help]
# usage: mySystem.sh [-lib_map_path]
# usage: mySystem.sh [-noclean_files]
# usage: mySystem.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'mySystem.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64 -timescale=1ps/1ps"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Script info
echo -e "mySystem.sh - Script generated by export_simulation (Vivado v2016.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" \
    "D:/Xilinx1/Vivado/2016.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx1/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" \
    "D:/Xilinx1/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv" \
    "D:/Xilinx1/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv" \
    "D:/Xilinx1/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv" \
    "D:/Xilinx1/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv" \
    "D:/Xilinx1/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv" \
    "D:/Xilinx1/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx1/Vivado/2016.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work gtwizard_ultrascale_v1_6_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/gtwizard_ultrascale_v1_6_2/hdl/verilog/gtwizard_ultrascale_v1_6_bit_synchronizer.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/gtwizard_ultrascale_v1_6_2/hdl/verilog/gtwizard_ultrascale_v1_6_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/gtwizard_ultrascale_v1_6_2/hdl/verilog/gtwizard_ultrascale_v1_6_gthe3_cpll_cal_freq_counter.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/gtwizard_ultrascale_v1_6_2/hdl/verilog/gtwizard_ultrascale_v1_6_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/gtwizard_ultrascale_v1_6_2/hdl/verilog/gtwizard_ultrascale_v1_6_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/gtwizard_ultrascale_v1_6_2/hdl/verilog/gtwizard_ultrascale_v1_6_gtwiz_reset.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/gtwizard_ultrascale_v1_6_2/hdl/verilog/gtwizard_ultrascale_v1_6_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/gtwizard_ultrascale_v1_6_2/hdl/verilog/gtwizard_ultrascale_v1_6_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/gtwizard_ultrascale_v1_6_2/hdl/verilog/gtwizard_ultrascale_v1_6_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/gtwizard_ultrascale_v1_6_2/hdl/verilog/gtwizard_ultrascale_v1_6_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/gtwizard_ultrascale_v1_6_2/hdl/verilog/gtwizard_ultrascale_v1_6_reset_synchronizer.v" \
    "$ref_dir/../../../../prj_MyKcu105_TI.srcs/sources_1/bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/gtwizard_ultrascale_v1_6_2/hdl/verilog/gtwizard_ultrascale_v1_6_reset_inv_synchronizer.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/sim/gtwizard_ultrascale_v1_6_gthe3_channel.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/sim/mySystem_jesd204_phy_0_gt_gthe3_channel_wrapper.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/sim/mySystem_jesd204_phy_0_gt_gtwizard_gthe3.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/sim/mySystem_jesd204_phy_0_gt_gtwizard_top.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/ip_0/sim/mySystem_jesd204_phy_0_gt.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_block.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_sync_block.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_support.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_gt_common_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_6_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/gtwizard_ultrascale_v1_6_gthe3_common.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_gt_common.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0_reset_control.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_phy_0/synth/mySystem_jesd204_phy_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work jesd204_v7_0_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" \
    "$ref_dir/../../../ipstatic/jesd204_v7_0/hdl/jesd204_v7_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0_block.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/axi_ipif/mySystem_jesd204_rx_0_address_decoder.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0_register_decode.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/axi_ipif/mySystem_jesd204_rx_0_axi_lite_ipif.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/axi_ipif/mySystem_jesd204_rx_0_counter_f.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/axi_ipif/mySystem_jesd204_rx_0_pselect_f.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/axi_ipif/mySystem_jesd204_rx_0_slave_attachment.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0_sync_block.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0_count_err.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_jesd204_rx_0/synth/mySystem_jesd204_rx_0.v" \
    "$ref_dir/../../../bd/mySystem/ipshared/user.org/leds_v1_1/sources_1/imports/leds/leds.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_leds_0_0/sim/mySystem_leds_0_0.v" \
    "$ref_dir/../../../bd/mySystem/ipshared/user.org/iobufs_ti_v2_2/sources_1/imports/iobufs_ti/iobufs_ti.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_iobufs_i_1/sim/mySystem_iobufs_i_1.v" \
    "$ref_dir/../../../bd/mySystem/hdl/mySystem.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_clk_wiz_0_0/mySystem_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/mySystem/ipshared/xilinx.com/xlconstant_v1_1/xlconstant.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlconstant_0_0/sim/mySystem_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlconstant_0_1/sim/mySystem_xlconstant_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work util_vector_logic_v2_0 $vhdlan_opts \
    "$ref_dir/../../../bd/mySystem/ipshared/xilinx.com/util_vector_logic_v2_0/hdl/util_vector_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_util_vector_logic_0_0/sim/mySystem_util_vector_logic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_Transport_layer_12DJxx_0_0/sim/mySystem_Transport_layer_12DJxx_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_util_vector_logic_0_8/sim/mySystem_util_vector_logic_0_8.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3" \
    "$ref_dir/../../../bd/mySystem/ipshared/xilinx.com/xlslice_v1_0/xlslice.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_0_8/sim/mySystem_xlslice_0_8.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_1_0/sim/mySystem_xlslice_1_0.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_0/sim/mySystem_xlslice_21_0.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_1/sim/mySystem_xlslice_21_1.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_2/sim/mySystem_xlslice_21_2.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_3/sim/mySystem_xlslice_21_3.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_4/sim/mySystem_xlslice_21_4.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_5/sim/mySystem_xlslice_21_5.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_6/sim/mySystem_xlslice_21_6.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_7/sim/mySystem_xlslice_21_7.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_8/sim/mySystem_xlslice_21_8.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_9/sim/mySystem_xlslice_21_9.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_10/sim/mySystem_xlslice_21_10.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_11/sim/mySystem_xlslice_21_11.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_12/sim/mySystem_xlslice_21_12.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_13/sim/mySystem_xlslice_21_13.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_14/sim/mySystem_xlslice_21_14.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_15/sim/mySystem_xlslice_21_15.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_16/sim/mySystem_xlslice_21_16.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_17/sim/mySystem_xlslice_21_17.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlslice_21_18/sim/mySystem_xlslice_21_18.v" \
    "$ref_dir/../../../bd/mySystem/ipshared/xilinx.com/xlconcat_v2_1/xlconcat.v" \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_xlconcat_0_2/sim/mySystem_xlconcat_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work util_reduced_logic_v2_0 $vhdlan_opts \
    "$ref_dir/../../../bd/mySystem/ipshared/xilinx.com/util_reduced_logic_v2_0/hdl/util_reduced_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mySystem/ip/mySystem_util_reduced_logic_1_3/sim/mySystem_util_reduced_logic_1_3.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.mySystem xil_defaultlib.glbl -o mySystem_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./mySystem_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./mySystem.sh -help\" for more information)\n"
        exit 1
      fi
     create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
     create_lib_mappings $2
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Create design library directory paths and define design library mappings in cds.lib
create_lib_mappings()
{
  libs=(xil_defaultlib xpm gtwizard_ultrascale_v1_6_2 jesd204_v7_0_0 util_vector_logic_v2_0 util_reduced_logic_v2_0)
  file="synopsys_sim.setup"
  dir="vcs"

  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  if [[ -e $dir ]]; then
    rm -rf $dir
  fi

  touch $file
  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#libs[*]}; i++ )); do
    lib="${libs[i]}"
    lib_dir="$dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
      mapping="$lib : $dir/$lib"
      echo $mapping >> $file
    fi
  done
  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi

}
# Remove generated data from the previous run and re-create setup files/library mappings
reset_run()
{
  files_to_remove=(ucli.key mySystem_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc mySystem_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./mySystem.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi

}

# Script usage
usage()
{
  msg="Usage: mySystem.sh [-help]\n\
Usage: mySystem.sh [-lib_map_path]\n\
Usage: mySystem.sh [-reset_run]\n\
Usage: mySystem.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
