# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 9
set_param xicom.use_bs_reader 1
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.cache/wt [current_project]
set_property parent.project_path C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/sources/ip_packaged/gen_mon [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/new/axi_stream_gen.sv
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/new/axi_stream_interface.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/axi_stream_lb.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/sources/hdl/debouncer.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/eth_axi_stream_gen_mon.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/eth_performance_monitor.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/hdl/mac_phy_wrapper.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/registers.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sync_registers.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/synchronizer_simple.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/tgm_address_decoder.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/tgm_axi_lite_ipif.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/tgm_counter_f.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/tgm_pselect_f.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/tgm_slave_attachment.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/user_registers_slave.v
  C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/sources/hdl/kcu105_10gbaser_top.v
}
add_files C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/mac_phy.bd
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_mac_ch1_0/synth/mac_phy_ten_gig_eth_mac_ch1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_mac_ch1_0/synth/mac_phy_ten_gig_eth_mac_ch1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_mac_ch1_0/synth/mac_phy_ten_gig_eth_mac_ch1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch1_0/ip_0/synth/mac_phy_ten_gig_eth_pcs_pma_ch1_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch1_0/ip_0/synth/mac_phy_ten_gig_eth_pcs_pma_ch1_0_gt.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch1_0/synth/mac_phy_ten_gig_eth_pcs_pma_ch1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch1_0/synth/mac_phy_ten_gig_eth_pcs_pma_ch1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch1_0/synth/mac_phy_ten_gig_eth_pcs_pma_ch1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_mac_ch0_0/synth/mac_phy_ten_gig_eth_mac_ch0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_mac_ch0_0/synth/mac_phy_ten_gig_eth_mac_ch0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_mac_ch0_0/synth/mac_phy_ten_gig_eth_mac_ch0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch0_0/ip_0/synth/mac_phy_ten_gig_eth_pcs_pma_ch0_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch0_0/ip_0/synth/mac_phy_ten_gig_eth_pcs_pma_ch0_0_gt.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch0_0/synth/mac_phy_ten_gig_eth_pcs_pma_ch0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch0_0/synth/mac_phy_ten_gig_eth_pcs_pma_ch0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch0_0/synth/mac_phy_ten_gig_eth_pcs_pma_ch0_0.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_system_ila_mac_phy1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_system_ila_mac_phy1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_system_ila_mac_phy1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_system_ila_mac_phy1_0/bd_0/ip/ip_0/bd_0423_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_system_ila_mac_phy1_0/bd_0/bd_0423_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/ip/mac_phy_system_ila_mac_phy1_0/mac_phy_system_ila_mac_phy1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/bd/mac_phy/mac_phy_ooc.xdc]

read_ip -quiet C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/axis_data_fifo_0.xci
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/axis_data_fifo_0_ooc.xdc]

read_ip -quiet C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/ip/bb_interface_fifo/bb_interface_fifo.xci
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/ip/bb_interface_fifo/bb_interface_fifo_ooc.xdc]

read_ip -quiet C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/ip/ila_interface/ila_interface.xci
set_property used_in_synthesis false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/ip/ila_interface/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/ip/ila_interface/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/ip/ila_interface/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/sources_1/ip/ila_interface/ila_interface_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/constrs_1/imports/constraints/kcu105_10gbaser.xdc
set_property used_in_implementation false [get_files C:/Users/dell/Desktop/kcu105_10gbaser_trd/hardware/vivado/runs/impl_run/10gbaser_trd.srcs/constrs_1/imports/constraints/kcu105_10gbaser.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top kcu105_10gbaser_top -part xcku040-ffva1156-2-e -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef kcu105_10gbaser_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file kcu105_10gbaser_top_utilization_synth.rpt -pb kcu105_10gbaser_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
