# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/ila_layer1_transfer/ila_layer1_transfer.xci
# IP: The module: 'ila_layer1_transfer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/ila_layer1_transfer/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_layer1_transfer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/ila_layer1_transfer/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_layer1_transfer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/ila_layer1_transfer/ila_layer1_transfer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_layer1_transfer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/ila_layer1_transfer/ila_layer1_transfer.xci
# IP: The module: 'ila_layer1_transfer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/ila_layer1_transfer/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_layer1_transfer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/ila_layer1_transfer/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_layer1_transfer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/ila_layer1_transfer/ila_layer1_transfer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_layer1_transfer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
