# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caohy/work/tpu_fs/tpu.srcs/sources_1/ip/dds_125m_i/dds_125m_i.xci
# IP: The module: 'dds_125m_i' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/work/tpu_fs/tpu.srcs/sources_1/ip/dds_125m_i/dds_125m_i_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_125m_i'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/caohy/work/tpu_fs/tpu.srcs/sources_1/ip/dds_125m_i/dds_125m_i.xci
# IP: The module: 'dds_125m_i' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/work/tpu_fs/tpu.srcs/sources_1/ip/dds_125m_i/dds_125m_i_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_125m_i'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
