# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/tpu_transmit.xdc

# IP: new/add_duc/add_duc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==add_duc || ORIG_REF_NAME==add_duc} -quiet] -quiet

# IP: new/mult_duc/mult_duc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_duc || ORIG_REF_NAME==mult_duc} -quiet] -quiet

# IP: new/sub_duc/sub_duc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_duc || ORIG_REF_NAME==sub_duc} -quiet] -quiet

# IP: new/dds_125m_i/dds_125m_i.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_125m_i || ORIG_REF_NAME==dds_125m_i} -quiet] -quiet

# IP: new/rs_encoder/rs_encoder.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rs_encoder || ORIG_REF_NAME==rs_encoder} -quiet] -quiet

# Block Designs: new/mac_phy/mac_phy.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mac_phy || ORIG_REF_NAME==mac_phy} -quiet] -quiet

# IP: new/mac_phy/ip/mac_phy_xlconstant_1b0_0/mac_phy_xlconstant_1b0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_1b0_0 || ORIG_REF_NAME==mac_phy_xlconstant_1b0_0} -quiet] -quiet

# IP: new/mac_phy/ip/mac_phy_xlconstant_1b1_0/mac_phy_xlconstant_1b1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_1b1_0 || ORIG_REF_NAME==mac_phy_xlconstant_1b1_0} -quiet] -quiet

# IP: new/mac_phy/ip/mac_phy_xlconstant_3b101_0/mac_phy_xlconstant_3b101_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_3b101_0 || ORIG_REF_NAME==mac_phy_xlconstant_3b101_0} -quiet] -quiet

# IP: new/mac_phy/ip/mac_phy_xlconstant_8b0_0/mac_phy_xlconstant_8b0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_8b0_0 || ORIG_REF_NAME==mac_phy_xlconstant_8b0_0} -quiet] -quiet

# IP: new/mac_phy/ip/mac_phy_ten_gig_eth_mac_ch0_0/mac_phy_ten_gig_eth_mac_ch0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mac_phy_ten_gig_eth_mac_ch0_0 || ORIG_REF_NAME==mac_phy_ten_gig_eth_mac_ch0_0} -quiet] -quiet

# IP: new/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch0_0/mac_phy_ten_gig_eth_pcs_pma_ch0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mac_phy_ten_gig_eth_pcs_pma_ch0_0 || ORIG_REF_NAME==mac_phy_ten_gig_eth_pcs_pma_ch0_0} -quiet] -quiet

# XDC: new/mac_phy/mac_phy_ooc.xdc
