# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/tpu_transmit.xdc

# Block Designs: new/mac_phy/mac_phy.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy || ORIG_REF_NAME==mac_phy} -quiet] -quiet

# IP: new/mac_phy/ip/mac_phy_xlconstant_1b0_0/mac_phy_xlconstant_1b0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_1b0_0 || ORIG_REF_NAME==mac_phy_xlconstant_1b0_0} -quiet] -quiet

# IP: new/mac_phy/ip/mac_phy_xlconstant_1b1_0/mac_phy_xlconstant_1b1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_1b1_0 || ORIG_REF_NAME==mac_phy_xlconstant_1b1_0} -quiet] -quiet

# IP: new/mac_phy/ip/mac_phy_xlconstant_3b101_0/mac_phy_xlconstant_3b101_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_3b101_0 || ORIG_REF_NAME==mac_phy_xlconstant_3b101_0} -quiet] -quiet

# IP: new/mac_phy/ip/mac_phy_xlconstant_8b0_0/mac_phy_xlconstant_8b0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_8b0_0 || ORIG_REF_NAME==mac_phy_xlconstant_8b0_0} -quiet] -quiet

# IP: new/mac_phy/ip/mac_phy_ten_gig_eth_mac_ch0_0/mac_phy_ten_gig_eth_mac_ch0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_ten_gig_eth_mac_ch0_0 || ORIG_REF_NAME==mac_phy_ten_gig_eth_mac_ch0_0} -quiet] -quiet

# IP: new/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch0_0/mac_phy_ten_gig_eth_pcs_pma_ch0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_ten_gig_eth_pcs_pma_ch0_0 || ORIG_REF_NAME==mac_phy_ten_gig_eth_pcs_pma_ch0_0} -quiet] -quiet

# IP: new/bb_interface_fifo/bb_interface_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bb_interface_fifo || ORIG_REF_NAME==bb_interface_fifo} -quiet] -quiet

# XDC: new/mac_phy/mac_phy_ooc.xdc
