# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dell/Desktop/TPU_pr/tpu/tpu.srcs/sources_1/ip/dds_upfir/dds_upfir.xci
# IP: The module: 'dds_upfir' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/TPU_pr/tpu/tpu.srcs/sources_1/ip/dds_upfir/dds_upfir_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_upfir'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/dell/Desktop/TPU_pr/tpu/tpu.srcs/sources_1/ip/dds_upfir/dds_upfir.xci
# IP: The module: 'dds_upfir' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/TPU_pr/tpu/tpu.srcs/sources_1/ip/dds_upfir/dds_upfir_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_upfir'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
