# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/add_ddc/add_ddc.xci
# IP: The module: 'add_ddc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/add_ddc/add_ddc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_ddc'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/add_ddc/add_ddc.xci
# IP: The module: 'add_ddc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/add_ddc/add_ddc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add_ddc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
