# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/kcu105_10gbaser.xdc

# IP: new/tpu_source/ip/axis_fifo_t8/axis_fifo_t8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_fifo_t8 || ORIG_REF_NAME==axis_fifo_t8} -quiet] -quiet

# IP: new/tpu_source/ip/axis_fifo_t/axis_fifo_t.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_fifo_t || ORIG_REF_NAME==axis_fifo_t} -quiet] -quiet

# IP: new/tpu_source/ip/ddc_out_fifo/ddc_out_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddc_out_fifo || ORIG_REF_NAME==ddc_out_fifo} -quiet] -quiet

# IP: new/tpu_source/ip/sub_ddc/sub_ddc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_ddc || ORIG_REF_NAME==sub_ddc} -quiet] -quiet

# IP: new/tpu_source/ip/mult_ddc/mult_ddc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_ddc || ORIG_REF_NAME==mult_ddc} -quiet] -quiet

# IP: new/tpu_source/ip/add_ddc/add_ddc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_ddc || ORIG_REF_NAME==add_ddc} -quiet] -quiet

# IP: new/tpu_source/ip/duc_out_fifo/duc_out_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==duc_out_fifo || ORIG_REF_NAME==duc_out_fifo} -quiet] -quiet

# IP: new/tpu_source/ip/add_duc/add_duc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_duc || ORIG_REF_NAME==add_duc} -quiet] -quiet

# IP: new/tpu_source/ip/mult_duc/mult_duc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_duc || ORIG_REF_NAME==mult_duc} -quiet] -quiet

# IP: new/tpu_source/ip/sub_duc/sub_duc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_duc || ORIG_REF_NAME==sub_duc} -quiet] -quiet

# IP: new/tpu_source/ip/dds_125m_q/dds_125m_q.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_125m_q || ORIG_REF_NAME==dds_125m_q} -quiet] -quiet

# IP: new/tpu_source/ip/dds_125m_i/dds_125m_i.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_125m_i || ORIG_REF_NAME==dds_125m_i} -quiet] -quiet

# IP: new/tpu_source/ip/rs_decoder/rs_decoder.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rs_decoder || ORIG_REF_NAME==rs_decoder} -quiet] -quiet

# IP: new/tpu_source/ip/rs_encoder/rs_encoder.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rs_encoder || ORIG_REF_NAME==rs_encoder} -quiet] -quiet

# Block Designs: bd/mac_phy/mac_phy.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy || ORIG_REF_NAME==mac_phy} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_xlconstant_1b0_0/mac_phy_xlconstant_1b0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_1b0_0 || ORIG_REF_NAME==mac_phy_xlconstant_1b0_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_xlconstant_1b1_0/mac_phy_xlconstant_1b1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_1b1_0 || ORIG_REF_NAME==mac_phy_xlconstant_1b1_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_xlconstant_3b101_0/mac_phy_xlconstant_3b101_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_3b101_0 || ORIG_REF_NAME==mac_phy_xlconstant_3b101_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_xlconstant_8b0_0/mac_phy_xlconstant_8b0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_xlconstant_8b0_0 || ORIG_REF_NAME==mac_phy_xlconstant_8b0_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_ten_gig_eth_mac_ch1_0/mac_phy_ten_gig_eth_mac_ch1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_ten_gig_eth_mac_ch1_0 || ORIG_REF_NAME==mac_phy_ten_gig_eth_mac_ch1_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch1_0/mac_phy_ten_gig_eth_pcs_pma_ch1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_ten_gig_eth_pcs_pma_ch1_0 || ORIG_REF_NAME==mac_phy_ten_gig_eth_pcs_pma_ch1_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_ten_gig_eth_mac_ch0_0/mac_phy_ten_gig_eth_mac_ch0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_ten_gig_eth_mac_ch0_0 || ORIG_REF_NAME==mac_phy_ten_gig_eth_mac_ch0_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_ten_gig_eth_pcs_pma_ch0_0/mac_phy_ten_gig_eth_pcs_pma_ch0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_ten_gig_eth_pcs_pma_ch0_0 || ORIG_REF_NAME==mac_phy_ten_gig_eth_pcs_pma_ch0_0} -quiet] -quiet

# IP: bd/mac_phy/ip/mac_phy_system_ila_mac_phy1_0/mac_phy_system_ila_mac_phy1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mac_phy_system_ila_mac_phy1_0 || ORIG_REF_NAME==mac_phy_system_ila_mac_phy1_0} -quiet] -quiet

# IP: /home/caohy/work/kcu_10gbaser_tpu/10gbaser_trd.srcs/axis_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# XDC: bd/mac_phy/mac_phy_ooc.xdc
