# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/bb_interface_fifo/bb_interface_fifo.xci
# IP: The module: 'bb_interface_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/bb_interface_fifo/bb_interface_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bb_interface_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/bb_interface_fifo/bb_interface_fifo.xci
# IP: The module: 'bb_interface_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dell/Desktop/board_test/kcu_10gbaser_tpu/10gbaser_trd.srcs/sources_1/ip/bb_interface_fifo/bb_interface_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bb_interface_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
