@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue May 26 17:19:44 +0800 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 57174fc282ef4b96bac6c4a167127b65 --incr --debug typical --relax --mt 2 -d "SIMULATION=1" -d "OOB_SIM=1" -L xlconstant_v1_1_6 -L xil_defaultlib -L ten_gig_eth_mac_v15_1_7 -L gtwizard_ultrascale_v1_7_7 -L ten_gig_eth_pcs_pma_v6_0_16 -L gigantic_mux -L axis_infrastructure_v1_1_0 -L axis_data_fifo_v2_0_2 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_behav xil_defaultlib.tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 57174fc282ef4b96bac6c4a167127b65 --incr --debug typical --relax --mt 2 -d "SIMULATION=1" -d "OOB_SIM=1" -L xlconstant_v1_1_6 -L xil_defaultlib -L ten_gig_eth_mac_v15_1_7 -L gtwizard_ultrascale_v1_7_7 -L ten_gig_eth_pcs_pma_v6_0_16 -L gigantic_mux -L axis_infrastructure_v1_1_0 -L axis_data_fifo_v2_0_2 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_behav xil_defaultlib.tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
