# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/axis_fifo_t8/axis_fifo_t8.xci
# IP: The module: 'axis_fifo_t8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/axis_fifo_t8/axis_fifo_t8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_fifo_t8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/axis_fifo_t8/axis_fifo_t8.xci
# IP: The module: 'axis_fifo_t8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/tpu_kcu105/tpu.srcs/sources_1/ip/axis_fifo_t8/axis_fifo_t8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_fifo_t8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
